name = "Assignment3"
uuid = "72fcdaec-93af-4fd4-9ba9-021f4d96b9e7"
authors = ["Forrest Laine <forrest.laine@vanderbilt.edu>"]
version = "0.1.0"

[deps]
Infiltrator = "5903a43b-9cc3-4c30-8d17-598619ec4e9b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
